### ISSUE TITLE
What's the nature of the companion data?  What to do if without them?

### ISSUE THREAD

**Issue by mlciv** [utahnlp/lapa-mrp#15]
## A. The nature of the companion data. 
 As shown in our README file, the data of MRP 2019 are provided in two formats:
 (1) raw sentences (with their corresponding annotations for training, in MRP format)
 (2) The companion folder and files contain features for those raw sentences in (1), such as pre-tokenized, pos-tagged, lemmas, dependency trees. (also in MRP format)
The part (2) companion data are just preprocessed linguistic features for the training data, and the provided companion files in MRP 2019 are optional to use. Please refer more details to http://mrp.nlpl.eu/2019/index.php?page=4 

You can use any off-the-shelf NLP tools to generate the features and write them into MRP format. Then you can directly use our models. 

## B. What to do if without the provided companion data?
To replicate the exact experiments in our paper, both (1) and (2) are required.  However, they are not publicly available.  
By default, our system will read MRP-format input features from those companion files (https://github.com/utahnlp/lapa-mrp/blob/1bb6d8c0b2009ddf3b16cde7dd579d78aac0d977/utility/data_helper.py#L224) 

You can use the Stanford CoreNLP to preprocess, then transform them into MRP format,  I have tried those alternative features(from StanfordCoreNLP) for AMR parsing, and they can get similar results.
	
The steps are as follows:
1. The following scripts can annotate the raw input sentences with StanfordCoreNLP and add the annotations into the original AMR format(comments in PENMAN notation)
	 https://github.com/utahnlp/lapa-mrp/blob/master/utility/amr_utils/AMR_FEATURE/src/convertingAMR.java  
	 https://github.com/utahnlp/lapa-mrp/blob/master/Expt/mrp_scripts/commands/amr2eng.sh 
	The output are as follows:
```
# ::id bolt12_64545_0527.1 ::date 2012-12-23T18:59:06 ::annotator SDL-AMR-09 ::preferred
# ::snt taking a look
# ::tok taking  a       look
# ::lem take    a       look
# ::pos VBG     DT      NN
# ::ner O       O       O
# ::save-date Mon Nov 25, 2013 ::file bolt12_64545_0527_1.txt
(l / look-01)
```
2.  read features from the above original AMR format, and transform it into the MRP format companion file.
By setting the input feature format as '.amr', the following function will read features from the above comments, and transform them into MRP format(The same companion file format)
https://github.com/utahnlp/lapa-mrp/blob/1bb6d8c0b2009ddf3b16cde7dd579d78aac0d977/src/preprocessing.py#L74

3. After generating the companion file, Then you can follow the original instructions as in the README file. 
For example, skipping the old preprocessing steps, the following script will build rules and amr inputs for the model. 
https://github.com/utahnlp/lapa-mrp/blob/master/Expt/mrp_scripts/commands/amr_prep_rules_data0.sh

**Comment by vmoutzouri** [comment]
Hello and thank you again for your assistance!
We encountered a problem with the initial splitting of our dataset, before moving on to the NLP annotation that you describe above - when trying to run mrp_split_amr.sh, the whole pre_logs folder seems to be missing. 
Is this folder something that should pre-exist?

**Comment by mlciv** [comment]
> Hello and thank you again for your assistance!
> We encountered a problem with the initial splitting of our dataset, before moving on to the NLP annotation that you describe above - when trying to run mrp_split_amr.sh, the whole pre_logs folder seems to be missing.
> Is this folder something that should pre-exist?

Thanks for pointing out this issue. 
The `pre_logs` folder is directly under the /Expt folder as shown in https://github.com/utahnlp/lapa-mrp/tree/master/Expt

The readme file missed the steps for manually creating the subfolders.  Please check out the latest version to fix it.

BTW, as you may have noticed the input files for the split is ".mrp" files. 
So if you are using the original version AMR dataset, which is already splitted, you actually don't need to split it again with that script. 

Since this code repo is based on MRP shared tasks, all the preprocessing and post-processing scripts are assuming the default settings of the unifed MRP format. We provide a unified framework for DM, PSD, and AMR parsing.   Hence,  without modification, the provided scripts are not directly supported for the original AMR files. I hope the suggested steps and code snippets will help in your cases. 

Besides the hard alignments model used in our paper, you probably have noticed the recent papers of using soft-attention as alignments and then modeling AMR as sequence-to-graph setting. For example, https://github.com/sheng-z/stog  https://github.com/jcyk/AMR-gs, these two projects are directly based on the original AMR dataset, I hope their code snippets will also help you.
